### ISSUE TITLE
Multikey patterns?

### ISSUE THREAD

**Issue by ghost** [potamides/modalawesome#1]
How can I set up multi key patterns?

For example, in the launcher mode, instead of using `t` to launch a terminal and `b` to launch a browser, can I set up `lt` to launch a terminal and `lb` to launch the browser?

**Comment by potamides** [comment]
Hi oponkork,
you can set up multi key patterns like this:
```lua
local command = {
  description = "launch terminal",
  pattern = {'l', 't'},
  handler = function() awful.spawn(terminal) end
}
```

**Comment by oponkork** [comment]
@potamides 
Alright, thanks a lot.

**Comment by ghost** [comment]
@potamides 

Thanks a lot. I am new to lua and awesomwm. I naively tried `pattern ={"lt"}` which didn't work.

**Comment by potamides** [comment]
No problem, glad I could help! I'm closing this issue now, since your problem has been resolved.
