### ISSUE TITLE
Allow common binding to have their own help section

### ISSUE THREAD

**Issue by Ph4ntomas** [potamides/modalawesome#5]
Hello !

In my configuration, I have some common bindings that were repeated in every modes.

I use these to switch from any mode to any mode, as well as some useful bindings (I have ? and : accessible at all time to show the help popup and launch commands).

I´ve got a fork that allow a special mode (common) to hold common bindings, that is merged with every other, then removed from mode list, in init.lua:process_modes. This let create_hotkey generate help for this common mode, before it´s merged with others and removed.

I can open a pull request if you think it can be useful.

It might be better to allow arbitrary name, but I used common in my own config, so I just hardcoded it that way

**Comment by potamides** [comment]
Hi @Ph4ntomas!

Yeah, this sound like a good idea and I think it makes sense to implement something like that. However I don't want to set a hardcoded name for that. I thought about it a little bit and the best idea I could come up with is to allow keys in the `modes` table to also be a table. These tables then should contain the names of all modes to which the corresponding bindings should be added to. This also has the benefit of giving the user higher control to which modes the bindings are being added to. For the hotkeys I would then create a new section with the concatenated key table as a name (e.g. with "/" as a separator). For your use case the mode table could then look like this for example:

```lua
local modes = {
  tag = { --[[ ... ]] },
  launcher = { --[[ ... ]] },
  layout = { --[[ ... ]] },
  [{"tag", "launcher", "layout"}] = { --[[ common bindings ]] }
}
```

If you have other ideas, please let me know :) I have some time in the next couple of days were I could implement this.

**Comment by Ph4ntomas** [comment]
Hey,

I totally agree with the fact that it should not be hardcoded. 
I do like the idea of a key made from a table, as it can allow several "common" modes, depending on what is needed.

However, I feel that creating a name by concatenation of the keys might make the hotkey popup less readable.
I do think it would be better if the user could override this/these name(s) instead.

I´m not sure how lua handles tables as keys, and I can´t test it right now, but is there a way this could work ?
```lua
local modes = {
  tag = { --[[ ... ]] },
  launcher = { --[[ ... ]] },
  layout = { --[[ ... ]] },
  [{name = "common", merges_with = {"tag", "launcher", "layout"}}] = { --[[ common bindings ]] }
}
```

That way it would allow for a clear name in hotkey popup, while maintaining the ability to create several common bindings as needed. Beside, if it work, it might be possible to check which way it was written, and either use `name` as is, or fallback on concatenating target tables.

**Comment by Ph4ntomas** [comment]
I know @Neh3maH is using my fork atm, maybe they can have some inputs on this issue

**Comment by potamides** [comment]
@Ph4ntomas,
you are absolutely right, it should be possible to configure a name for readability. I went with the following syntax however, since it's shorter and conveys the same information:
```lua
local modes = {
  tag = { --[[ ... ]] },
  launcher = { --[[ ... ]] },
  layout = { --[[ ... ]] },
  [{"tag", "launcher", "layout", name = "common"}] = { --[[ common bindings ]] }
}
```
The name field is optional, when it's not set, then the listed modes are concatenated with `/` as separator.

@Ph4ntomas, @Neh3maH I created a pull request, if you have the time, could you test it and tell me if it suits your needs?

**Comment by Ph4ntomas** [comment]
I´ll try to take a look tomorrow, see if it break my config or not :)

**Comment by Ph4ntomas** [comment]
I just realized I never answer here. As said on the #6, everything works perfectly on my end.

Thanks again

**Comment by potamides** [comment]
Ah my bad, I was busy the last couple of weeks and couldn't come back to it.
> The only issue I see, is that if you have lots of modes, the current syntax might become tedious.

I think this is an important point you address. Also now thinking about it there are some problems that arise when you use a table as a key (e.g. indexing). This issues could be easily avoided with some changes:
```lua
local modes = {
  tag = { --[[ ... ]] },
  launcher = { --[[ ... ]] },
  layout = { --[[ ... ]] },
  common = { merge=true, --[[ ... ]] }
}
```
Check this syntax for example, this would solve these issues. If you need more fine-grained control you could also supply a table with mode names instead of a boolean. Would that also fit your use case?

**Comment by Ph4ntomas** [comment]
> Check this syntax for example, this would solve these issues. If you need more fine-grained control you could also supply a table with mode names instead of a boolean. Would that also fit your use case?

That would indeed fix the potential issue I saw. I don't have that many modes (I use four or five modes in total), so both syntax works for me.

**Comment by potamides** [comment]
Okay perfect, I just implemented this updated behavior. If it now works for you, I'll finally merge this.

**Comment by Ph4ntomas** [comment]
Ok, I'm at work right now, I´ll try to test it this week-end.

**Comment by Ph4ntomas** [comment]
Hey, I had some free time today. Everything works perfectly on my end, both with `merge=true` and `merge={table}`. Thanks a lot !
