### ISSUE TITLE
[BUG] Special Keys recognised as pattern

### ISSUE THREAD

**Issue by Ph4ntomas** [potamides/modalawesome#7]
Hi, I just found a weird bug I had never noticed before. I think it has been introduced recently, as it begun when I tried the PR for common bindings.

When I hit arrow keys, the sequence grabbed is the name of said key. The issue is that "Left" match my "L" binding to switch to the tag on the right of my main tag.

**Comment by potamides** [comment]
Thanks for reporting this. I believe the bug was introduced with commit cc44ba4. The latest commit should fix this.

**Comment by Ph4ntomas** [comment]
It does, thanks ! I'm closing the issue then.
